

version: "3.8"

services:
  admin-service:
    build:
      context: ./AdminService
    container_name: admin-service
    ports:
      - "8000:5000" # Maps internal 5000 port to external 8000
    networks:
      - fooddeliverysystem
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  order-service:
    build:
      context: ./OrderService
    container_name: order-service
    ports:
      - "8001:5000" # Maps internal 5000 port to external 8001
    networks:
      - fooddeliverysystem
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  restaurant-service:
    build:
      context: ./RestaurantService
    container_name: restaurant-service
    ports:
      - "8002:5000" # Maps internal 5000 port to external 8002
    networks:
      - fooddeliverysystem
    environment:
      - SPRING_PROFILES_ACTIVE=prod

networks:
  fooddeliverysystem:
    driver: bridge
